services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_app
    ports:
      - "3001:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    env_file:
      - .env

  db:
    image: mysql:8.0 # Phiên bản MySQL hỗ trợ ARM
    platform: linux/arm64 # Chạy đúng nền tảng
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: product_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 3
      start_period: 30s

volumes:
  db_data:
