networks:
  go-net:
    driver: bridge

volumes:
  db_data:
    # Volume lưu trữ dữ liệu MySQL

services:
  mysql_db:
    image: mysql:8.0.33
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql # Lưu trữ dữ liệu MySQL
    env_file:
      - ./.env 
    restart: unless-stopped
    networks:
      - go-net

 
