// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package diContainer

import (
	"product_srv/internal/domain/users/controllers"
	"product_srv/internal/domain/users/services"
	"product_srv/internal/repositories"
)

// Injectors from wire.go:

// User Domain Injection
func InitUserDomain() (*user_controllers.UserController, error) {
	userRepository := repositories.NewUserRepository()
	userService := services.NewUserService(userRepository)
	userController := user_controllers.NewUserController(userService)
	return userController, nil
}
